### ISSUE TITLE
[ERROR] Could not retrieve cache sets, please try to restart

### ISSUE THREAD

**Issue by rianquinn** [IAIK/CJAG#3]
I know you have a FAQ answer for this, but I have tested 5 machines, and all of them but one return this error regardless of what parameters I use. I have tested IvyBridge, Haswell and Skylake, and the Skylake is the only machine to work. For both IvyBridge and Haswell I have tested both desktops and laptops. 

Any ideas on things to try?

**Comment by rianquinn** [comment]
To add to this, I was able to get some of the other machines to work, but I had to run it multiple times with the same parameters. Sometimes it would fail with this error, other times it would work.

**Comment by misc0110** [comment]
I might also be the case that the application did not get huge pages. You can try to increase the overall number of huge pages: "sudo sysctl -w vm.nr_hugepages=256".
