### ISSUE TITLE
The CJag could be run in Ubuntu with OpenStack?

### ISSUE THREAD

**Issue by daniellee83** [IAIK/CJAG#4]
I do some tests in Ubuntu with OpenStack,  set the same cache parameters with local machine,but it also tell me timeout. I want you give me some suggestions! Thank you!

**Comment by dgruss** [comment]
does the local machine and the machine with openstack have the same hardware configuration - especially, the same CPU model?

**Comment by daniellee83** [comment]
I build two Virtual Machine with OpenStack, the Operation System is Ubuntu 64bit, and I set them on the same physical machine.I give the physical machine's Cache parameters to CJAG，run them at the same time.But Sender and Receiver  also tell me timeout.Do i have something wrong steps?Thank you!

**Comment by misc0110** [comment]
Does it work if you run sender and receiver in the same virtual machine?

**Comment by daniellee83** [comment]
@misc0110 yes,it works,but it also tell me timeout.

**Comment by misc0110** [comment]
Ok, that is good. Then I would try to steadily increase the value of the "--delay" parameter, starting from something like 5.

**Comment by daniellee83** [comment]
@misc0110 Does the "--delay" parameter is the same in each CJAG?

**Comment by misc0110** [comment]
Yes, they have to be the same for both sender and receiver.

**Comment by daniellee83** [comment]
@misc0110 Does the "--delay" parameter has the Minimum and Maximum values?

**Comment by misc0110** [comment]
The "--delay" parameter is a multiplier for the timeouts. Thus, it has to be larger than 0, but there is no maximum. For large "--delay" parameter values everything is just (a lot) slower. On our test setups, we never required values larger than 10.
