### ISSUE TITLE
Query about cache slices

### ISSUE THREAD

**Issue by adilahmad17** [IAIK/CJAG#6]
Hi,

I had a question about the cache slices. The formula that you use, is it generic for all CPUs? As in my CPU has 4 slices and if i try getting the slice information, with get_slices(paddr, 4), should it work fine?

Thanks!

Here's what get_cpu_info and get_cache_info return:
`# of phy cores: 2, # of slices: 4
4096 KB, 16-way L3
`

**Comment by dgruss** [comment]
On 2017-05-07 22:23, Adil Ahmad wrote:
> I was looking at your github repo (https://github.com/IAIK/CJAG) and I
> had a question about the cache slices. The formula that you use, is it
> generic for all CPUs? As in my CPU has 4 slices and if i try getting the
> slice information, with get_slices(paddr, 4), should it work fine?

Yes, you're right!


Cheers,
Daniel

**Comment by adilahmad17** [comment]
Thanks! :)
